#!/bin/bash
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"


cd $DIR/../
. ./meta/env

[ ! -d $DIR/../meta/server ] && echo "Please symlink a server from avalon to /meta/server before release" && exit 1
. $DIR/../meta/server/env

storagePath="/storage/fzc"

backupPath="./backup/fzc"


echo "upload storage"
# ssh $ServerUser@$ServerIP -i $ServerRSA "sudo mkdir -p /storage"
# ssh $ServerUser@$ServerIP -i $ServerRSA "sudo mkdir -p $storagePath"
# rsync -e "ssh -i $ServerRSA" -aPziou $backupPath $ServerUser@$ServerIP:$storagePath 

# echo "restore mongodb database"
# ssh $ServerUser@$ServerIP -i $ServerRSA "sudo mongorestore --db $PROJECT_NAME $storagePath/dbbackup"
